a

diff --git a/.circleci/sub_config.yml b/.circleci/sub_config.yml
--- a/.circleci/sub_config.yml
+++ b/.circleci/sub_config.yml
@@ -30,54 +30,86 @@ jobs:
         default: ""
     executor:
       name: default
+    working_directory: ~/work
     steps:
       - checkout
+      - run:
+          name: setup 
+          command: |
+            pip3 install ruamel.yaml
       - run:
           name: execute_script
           command: |
             set -x
-            echo Hello, World!
-            rel="<< parameters.rel >>"
-            file="<< parameters.file >>"
-            echo rel=${rel} file=${file}
-            pwd
-            env
-            uname -a
-            lsb_release -a
-            id
-            git branch
-            git status
-            git diff --name-only origin/main
-            pip3 install ruamel.yaml
-            python3 --version
-            pip3 list
-            which jq
-
+            WORK_DIR="~/work"
+            # check target 
+            BASE_REPO=main
+            git diff --names-only ${BASE_REPO} > target.list
+            SUBSIDIARY_COUNT=$(awk -F/ '{print $1}' target.list | uniq | wc -l)
+            ENV_COUNT=$(awk -F/ '{print $2}' target.list | uniq | wc -l)
+            if [ ${SUBSIDIARY_COUNT} -ne 1 -a ${ENV_COUNT} -ne 1 ]; then
+              echo "multi target error"
+              exit 1
+            fi
+            # check yaml update
+            while read line
+            do 
+              # python3 
+            done < <(cat target.list)
   execute_pr:
     executor:
       name: default
+    working_directory: ~/work
     steps:
       - checkout
+      - run:
+          name: setup 
+          command: |
+            pip3 install ruamel.yaml
       - run:
           name: execute_update_script
           command: |
             set -x
-            echo update script
-            pip3 install ruamel.yaml
-            GIT_USER="newtechd-kras"
-            echo $GIT_TOKEN
-            BRANCH_NAME="release-test"
-            REPO_NAME="test-ci-release"
-            git config --global user.email "kras@newtechd.com"
-            git config --global user.name "Yasunari Inoue"
-            git clone https://$GIT_USER:$GIT_TOKEN@github.com/newtechd-kras/$REPO_NAME.git
-            cd $REPO_NAME
-            git checkout -b $BRANCH_NAME
-            # git checkout -b $BRANCH_NAME origin/new_branch
-            cp ../test-ci/rel/jp/rel.txt .
-            git add .
-            git commit -m "add"
-            git push origin $BRANCH_NAME
+            WORK_DIR="~/work"
+            BASE_REPO=main
+            git diff --names-only ${BASE_REPO} > target.list
+            SUBSIDIARY=$(awk -F/ '{print $1}' target.list | uniq)
+            ENV=$(awk -F/ '{print $2}' target.list | uniq)
+            TARGET_REPO_LIST="~/work/"
+            # execute yaml update
+            TARGET_SERVICE_LIST="${WORK_DIR}/${SUBSIDIARY}/${ENV}/service.list"
+            while read service
+            do 
+              echo "service=${service}"
+              while read target
+              do 
+                # python3 
+                echo "target"
+              done < <(cat target.list)
+            done < <(cat ${TARGET_SERVICE_LIST})
+            # PR
+            # date=$(date '+%Y%m%d%H%M%S')
+            # GIT_USER="newtechd-kras"
+            # echo $GIT_TOKEN
+            # BASE_NAME="newtechd-kras"
+            # BRANCH_NAME="release-test"
+            # REPO_NAME="test-ci-release"
+            # git config --global user.email "kras@newtechd.com"
+            # git config --global user.name "Yasunari Inoue"
+            # git clone https://$GIT_USER:$GIT_TOKEN@github.com/$BASE_NAME/$REPO_NAME.git
+            # cd $REPO_NAME
+            # git checkout -b $BRANCH_NAME
+            # # git checkout -b $BRANCH_NAME origin/new_branch
+            # cp ../test-ci/rel/jp/rel.txt .
+            # git add .
+            # git commit -m "add"
+            # git push origin $BRANCH_NAME
+            # PR_TITLE="add release PR"
+            # PR_BASE="main"
+            # curl -X POST -u "$GIT_USER:$GIT_TOKEN" "https://api.github.com/repos/$BASE_NAME/$REPO_NAME/pulls" -H "Accept: application/vnd.github.v3+json" -d "{\"title\":\"$PR_TITLE\",\"head\":\"$BRANCH_NAME\",\"base\":\"PR_BASE\"}" > response.json
+            # URL=$(jq -r .url response.json)
+            # curl -u "$GIT_USER:$GIT_TOKEN" -X PUT -H "Accept: application/vnd.github.v3+json" $URL/merge
+            # curl -s -X DELETE -u "$GIT_USER:$GIT_TOKEN" https://api.github.com/repos/$BASE_NMAE/$REPO_NAME/git/refs/heads/$BRANCH_NAME
 
   #
   no_job_execution:
